#!/bin/bash
# 
# Deb package postrm script for API Server
#
# echo ""
# echo "Reload systemd manager configuration..."
# systemctl daemon-reload
echo -e "POST RM called with: \ntarg1: $1\ntarg2: $2\ntarg3: $3\ntarg4: $4" 