#!/bin/bash
# 
# Deb package prerem script for API Server
#
# echo ""
# name="api-server"
# if [[ $(systemctl list-units --all -t service --full --no-legend "$name.service" | sed 's/^\s*//g' | cut -f1 -d' ') == $name.service ]]; then
#     if systemctl is-active --quiet "$name.service" ; then
#         echo "Stopping $name service..."
#         systemctl stop api-server
#     fi    
#     if systemctl is-enabled --quiet "$name.service" ; then
#         echo "Disabling $name service..."
#         systemctl disable api-server
#     fi    
# fi
#
############ LIST OF SQL SCRIPTS TO BE EXECUTED ############
# list of SQL scripts to be executed in the format:
# 	[database] <path to sql script> <description>
read -r -d '' scripts << EOF
    "$db" "/etc/cma-recorder/drop_event_view.sql" "Drop 'event_view' view..."
    "$db" "/etc/cma-recorder/drop_event.sql" "Drop 'event' table..."
EOF

############ PRE RM ACTIONS ############
RED='\033[0;31m'
BLUE='\033[0;34m'
GRAY='\033[1;30m'
YELLOW='\033[1;93m'
NC='\033[0m' # No Color
echo -e ""
echo -e "${YELLOW}All historical data stored in the ${NC}"
echo -e "${YELLOW}database will be permanently removed... ${NC}"
echo -e ""
read -p "Are you sure (yes/no) ? " -n 1 -r REPLY
echo
echo "Reply: $REPLY"
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "Clearing the historian data..."

    ############ LOAD TO DB VIA PSQL ############
    regex='\"([^\"]*?)\"[ \t]+\"([^\"]+?)\"([ \t]+\"([^\"]+?)\")?'
    while IFS= read -r row; do
        [[ $row =~ $regex ]]
        connect=${BASH_REMATCH[1]:=""}
        path=${BASH_REMATCH[2]:="${RED}not specified${NC}"}
        description=${BASH_REMATCH[4]:="Unnamed SQL script..."}
        echo ""
        echo -e "$description"
        echo -e "\t${GRAY}from file:${NC} $path"
        echo -e "\t${GRAY}connect to database:${NC} $connect"
        if [ -z "$connect" ]; then
            sudo -i -u postgres psql --echo-errors -a -f "$path"
        else
            sudo -i -u postgres psql --echo-errors --dbname=$connect -a -f "$path"
        fi
    done <<< "$scripts"

    echo "Clearing - done"
else
    echo "The historical data stays unchanged in the database"
fi
echo -e ""
echo -e "PRE RM called with: \ntarg1: $1\ntarg2: $2\ntarg3: $3\ntarg4: $4" 
