# 
# This is template of the CMA Serveer with CMA Recorder service config for the API Server application
# Rename this file to config.yaml to activate it
#
address: '0.0.0.0:8080'       # self ip:port address where API service will be alvalible
services:                      # list of currently avalible API services
    - database-postgres-crane-data-server:
        name: 'crane_data_server'
        type: postgres
        path: 'localhost:5432'
        user: crane_data_server
        pass: 00d0-25e4-*&s2-ccds
        # replaceNullWithDefault:
    - py-test-script:                   # internal unique API service name
        name: 'py-test'          # the name of the python script (must be specified in the API request, field 'path')
        type: python             # the type of the service
        path: 'extensions/scripts/script_tamplate.py'  # the path to the python script file
        user: root               # can be used to restrict assecc to the python script
        pass: root               # can be used to restrict assecc to the python script
